### ISSUE TITLE
Indenting is incorrect

### ISSUE THREAD

**Issue by juszczakn** [reasonml-editor/reason-mode#22]
From the `simple` example generated via `bsb -init my-simple-app -theme react`, I ran `indent-region` and this was the result. 

it appears that it is just repeatedly indenting, even when it is not needed. 

```
let make ::message _children => {
  ...component,
    render: fun self =>
        <div onClick=(self.handle handleClick)> (ReasonReact.stringToElement message) </div>
        };
```

**Comment by anmonteiro** [comment]
I can't repro this. are you using latest master?

**Comment by juszczakn** [comment]
Just pulled, apparently not. Setup a few weeks ago, was on `8b92f6e`. Thanks, closing.
