### ISSUE TITLE
reason-react

### ISSUE THREAD

**Issue by socksrust** [reasonml-editor/reason-mode#23]
is there any way to solve the reason-react identations?

https://github.com/reasonml/reason-react

**Comment by anmonteiro** [comment]
What problem are you having? Make sure you're running the latest release from Melpa

**Comment by socksrust** [comment]
<img width="1440" alt="screen shot 2017-10-22 at 20 08 47" src="https://user-images.githubusercontent.com/13947203/31866915-d67ad1b4-b764-11e7-81fb-0e42e92dc416.png">

**Comment by socksrust** [comment]
the components are all on the same line when i tab

**Comment by anmonteiro** [comment]
Thanks, I can repro. Will have a look soon

**Comment by socksrust** [comment]
@anmonteiro news?

update: when i save the file it render the code correctly!
