### ISSUE TITLE
Is there any reason for not to register at Melpa?

### ISSUE THREAD

**Issue by Ailrun** [reasonml-editor/reason-mode#27]
In README.md, you said

> At the moment this plugin is not deployed on Elpa

I know it's hard to be registered at Elpa. However, registering at  Melpa is not that tough and even, simple.
Furthermore, there're many emacsens using Melpa to install their packages.

When I try to use `flow`, I found same issue. Do facebook guys hate Melpa?

**Comment by anmonteiro** [comment]
This package is indeed deployed to Melpa. See https://melpa.org/#/reason-mode

> When I try to use flow, I found same issue. Do facebook guys hate Melpa?

This package is **not** maintained by Facebook, and not related to Flow at all. It's maintained by the community, and such remarks are not appreciated as they serve absolutely no purpose other than hindering community efforts and alienating potential users and contributors.

**Comment by Ailrun** [comment]
@anmonteiro Sorry for that. I didn't notice it.

**Comment by Ailrun** [comment]
@anmonteiro IMO, adding such information on README.md is better for Reason newbies.
If you allow for me to fix my question, My adjusted question is
"Why didn't you guys add such info on README.md?"

**Comment by Ailrun** [comment]
Or, sending PR instead of bringing question up is  better way to communicate in Reason community?

**Comment by arichiardi** [comment]
By the way it is kind of my fault :smile: I refactored out the project from the reason repo but never had time to give it too much love.
I agree with Antonio that there are better way to handle and phrase things. PR-ing is of course even better.

**Comment by Ailrun** [comment]
@arichiardi
Phrasing is my fault. I thought these repos 
are maintained by FB. I'm really sorry my expression make someone feel bad.
There's some communities don't prefer PR before making relevant Issue...
If Reason community is not the case and you guys not yet start to fix README.md, can I make the PR?

**Comment by anmonteiro** [comment]
I've been meaning to add it to the README. PR welcome
