### ISSUE TITLE
Hook up Continuos Integration

### ISSUE THREAD

**Issue by arichiardi** [reasonml-editor/reason-mode#3]
This is the first step binging to an Elpa release. We can follow:

 * https://github.com/ananthakumaran/tide/blob/master/.travis.yml
 * https://github.com/magit/magit/blob/master/.travis.yml
 * https://github.com/bbatsov/projectile/blob/master/travis/provision.sh (different approach with PPA)
 * https://github.com/magnars/s.el/blob/master/.travis.yml (this last one looks good, with PPA)

I think we can safely start our support from Emacs 24.5 as it was the one that introduced the fancy string functions. I need to go through the code base again for double checking this.

**Comment by anmonteiro** [comment]
fixed https://github.com/reasonml-editor/reason-mode/commit/6693b5ec250ba6e92f00ac578d7905f11d12b2f9
