### ISSUE TITLE
Sync keyword list

### ISSUE THREAD

**Issue by sorawee** [reasonml-editor/reason-mode#37]
There are some missing keywords that are not highlighted. `exception` and `raise` are examples, and there are probably more.

**Comment by anmonteiro** [comment]
Nice catch, would you like to add them to this list? https://github.com/reasonml-editor/reason-mode/blob/master/reason-mode.el#L70

**Comment by sorawee** [comment]
I originally didn't want to do it because I didn't know the complete list of keywords. But then I realized I could just look at the lexer and other editors' language configuration file. So, here's the PR: #38 :)

**Comment by anmonteiro** [comment]
fixed by #38
