### ISSUE TITLE
Is it possible to jump to a definition with marker stack?

### ISSUE THREAD

**Issue by gamb** [reasonml-editor/reason-mode#47]
I've got `merlin-locate` working okay, but it doesn't pop the marker stack. AFAICT `merlin-jump` won't work with Reason files? Just curious how other people do this.

**Comment by gamb** [comment]
…Ignore me this is fine with `merlin-pop-stack` :disappear:

**Comment by Khady** [comment]
And you can use the integration with xref to have all the common behaviors

**Comment by gamb** [comment]
@Khady Oh thanks, that sounds good, have you got an example of xref integration?

**Comment by gamb** [comment]
Ooh nice, I'd just added `("M-." . merlin-locate)` and `M-,` 😄 https://github.com/Khady/emacs.d/blob/master/config.org#merlin
